---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
```

Read column names
```{r}
column.names <- read_csv("ColumnNames.csv", col_names = F)
```


Read csv data
```{r}
data <- read_csv("data/20211231_Experiment.csv", skip = 5, col_names = column.names$X1)
```
```{r}
data_clean <- data %>%
  select(-ends_with(".Clo"), 
         -ends_with(".Teq"), 
         -ends_with(".PMV"), 
         -ends_with(".PPD"), 
         -ends_with(".SET"), 
         -ends_with(".ET"), 
         -starts_with("All"), 
         -starts_with("GroupA"), 
         -starts_with("GroupB"),
         -Runtime) %>%
  mutate(Time = mdy_hms(Time)) %>%
  head(-2) # removes last 1 minute of data
```


```{r}
data_experiemnt1 <- data_clean %>%
  filter(Time > mdy_hms("12/31/2021 03:30:00 PM") & Time < mdy_hms("12/31/2021 04:57:00 PM")) %>%
  pivot_longer(cols = ends_with(".T") | ends_with(".P"),
               names_to = c("BodySegment", "Metric"),
               names_sep = "[.]") %>%
  pivot_wider(names_from = Metric, names_prefix = "Metric.", values_from = value) %>%
  group_by(BodySegment) %>%
  mutate(deltaT= Metric.T - lag(Metric.T, default = first(Metric.T))) %>%
  mutate(deltaP= Metric.P - lag(Metric.P, default = first(Metric.P))) %>%
  slice_tail(n = 20) %>%
  summarise(max.deltaT = max(deltaT),
            mean.deltaT = mean(deltaT)) %>%
  mutate(max.deltaT = round(max.deltaT, digits = 2)) %>%
  mutate(mean.deltaT = round(mean.deltaT, digits = 2)) 

```


```{r}
ggplot(data_experiemnt1, aes(x = Time, deltaT)) +
  geom_line(aes(colour = BodySegment)) +
  geom_hline(yintercept = c(-0.2, 0.2)) +
  theme_minimal()
```

```{r}
ggplot(data_experiemnt1, aes(x = Time, deltaP)) +
  geom_line(aes(colour = BodySegment)) +
  #geom_hline(yintercept = c(-0.2, 0.2)) +
  theme_minimal()
```

```{r}
data <- data16_2 %>%
  full_join(data28_2) %>%
  mutate(Time = mdy_hm(Time)) %>%
  filter(Setting == "Comfort") %>%
  group_by(Chamber.SetPoint) %>%
  slice(tail(row_number(), 20)) %>%
  pivot_longer(cols = ends_with(".T") | ends_with(".P"),
               names_to = c("BodySegment", "Metric"),
               names_sep = "[.]") %>%
  pivot_wider(names_from = Metric, names_prefix = "Metric.", values_from = value) %>%
  group_by(Chamber.SetPoint, BodySegment) %>%
  summarise(Ta = mean(Chamber.SetPoint), Ts = mean(Metric.T), P = mean(Metric.P)) %>%
  mutate(h = P/(Ts-Ta))

data_all 
```
```{r}
ggplot(data_all, aes(x = Ta, y = h)) + geom_line(aes(colour = BodySegment)) +
  scale_y_continuous(limits = c(0,15)) +
  theme_minimal()

```
```{r}
data_all <- data_all %>%
  filter(BodySegment == "All")

ggplot(data_all, aes(x = Ta, y = h)) + geom_line() +
  scale_y_continuous(limits = c(0,15)) +
  theme_minimal()

```

