---
title: "FurtherAnalysis"
author: "Arfa Aijazi"
date: '2022-10-31'
output: github_notebook
---


```{r message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(tidyverse)
library(lubridate)
library(knitr)
library(ggpubr)
library(zoo)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Set plot theme and colors
theme_custom = function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(strip.background = element_blank()) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(legend.title = element_blank()) +
    theme(axis.title = element_blank()) +
    theme(text = element_text(size = 7, colour = "#000000"))
}
```

```{r}
# Load TMY3 weather file for Dallas
tmy3_file <- paste0("USA_TX_Dallas-Fort.Worth.Intl.AP.722590_TMY3.epw")
dallas_tmy3 <- read.csv(file = tmy3_file, header = FALSE, skip = 8, nrows=8760)
dallas_tmy3 <- dallas_tmy3 %>%
  mutate(Date = paste0("2021-",V2, "-", V3, " ", V4, ":00")) %>%
  rename(hourly_TMY3 = V7) %>%
  select(Date, hourly_TMY3) %>%
  mutate(Date = parse_date_time(Date, "ymd_HM"))

last7 <- dallas_tmy3 %>%
  slice_tail(n = 167) %>%
  select(Date, hourly_TMY3) 
year(last7$Date) <- year(last7$Date)-1

dallas_tmy3 <- full_join(last7, dallas_tmy3) %>%
  select(Date, hourly_TMY3) %>%
  mutate(rollmean_TMY3 = rollmean(hourly_TMY3, 168, fill = NA, align = "right")) %>% # prevailing 7-day average temperature
  drop_na()

```

```{r}
# Load historical weather file for Dallas
historical_file <- "dallas_historicalT.csv"
dallas_historical <- read.csv(file = historical_file, header = TRUE)
colnames(dallas_historical)[1] = "Date"

dallas_historical <- dallas_historical %>%
  mutate(Date = parse_date_time(Date, "mdy_HM")) %>%
  mutate(hourly_Historical = (hourly_Historical-32)*5/9) %>% # Convert F to C
  mutate(rollmean_Historical = rollmean(hourly_Historical, 168, fill = NA, align = "right")) %>% # prevailing 7-day average temperature
  drop_na()
```

```{r}
# Merge
dallas <- inner_join(dallas_tmy3, dallas_historical) %>%
  pivot_longer(!Date, names_to = c("metric", "type"), names_sep = "_", values_to = "Temperature") %>%
  pivot_wider(names_from = metric, values_from = Temperature) %>%
  mutate(none = ifelse(between(day(Date), 14, 17),(0.4*hourly) + 17.1, (0.1*hourly) + 22.0)) %>%
  mutate(passive = ifelse(between(day(Date), 14, 17), none + 6, none)) %>%
  mutate(heated_blanket = ifelse(between(day(Date), 14, 17), none + 4.5, none)) %>%
  pivot_longer(cols = none:heated_blanket, names_to = "intervention", values_to = "Temperature") %>%
  mutate(comfort = (0.255*rollmean) + 18.9) %>%
  mutate(comfort_min = comfort - 6.9/2) %>%
  select(-comfort)  %>%
  mutate(type = factor(type)) %>%
  mutate(intervention = factor(intervention, levels = c("none", "passive", "heated_blanket"))) %>%
  filter(type == "Historical")
  
```
```{r}
dallas_calc <- dallas %>%
  mutate(difference = Temperature - comfort_min) %>%
  mutate(cold = ifelse(difference < 0, TRUE, FALSE)) %>%
  mutate(sleep = ifelse(hour(Date) >= 22 | hour(Date) < 7, TRUE, FALSE)) %>%
  mutate(outage = ifelse(between(day(Date), 14, 17), TRUE, FALSE)) %>%
  filter(sleep == TRUE) %>%
  filter(outage == TRUE) %>%
  filter(cold == TRUE) %>%
  group_by(type, intervention, .drop = FALSE) %>%
  tally()

dallas_calc
```


```{r}
ggplot(dallas, aes(x = Date, y = Temperature)) + 
  annotate("rect", xmin = parse_date_time("2021-02-14 0:00", "ymd_HM"), xmax = parse_date_time("2021-02-18 0:00", "ymd_HM"), ymin = -Inf, ymax = Inf, alpha = 0.2) +
  annotate("text", x = parse_date_time("2021-02-14 12:00", "ymd_HM"), y = Inf, label = "Power Outage") +
  geom_line(aes(linetype = intervention)) + 
  geom_line(aes(y = comfort_min), colour = "#9970AB") +
  theme_custom() +
  ylab("Ambient temperature (C)")

ggsave("DallasColdSnap.pdf", width = 6.5, height = 3, units = "in")
```

