---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggpubr)
```

```{r}
data32 <- read_csv("20211124_Warmup.csv")
data28 <- read_csv("20211125_Warmup.csv")
data18 <- read_csv("20211126_Warmup.csv")
data16 <- read_csv("20211127_Warmup.csv")
data16_2 <- read_csv("20211130_Warmup.csv")
data28_2 <- read_csv("20211201_Warmup.csv")

data_all <- data32 %>%
  full_join(data28) %>%
  full_join(data18) %>%
  full_join(data16) %>%
  full_join(data16_2) %>%
  full_join(data28_2) %>%
  mutate(Time = mdy_hm(Time)) %>%
  pivot_longer(cols = ends_with(".T") | ends_with(".P"),
               names_to = c("BodySegment", "Metric"),
               names_sep = "[.]") %>%
  filter(Setting != "Warmup") %>%
  mutate(Setting = factor(Setting, levels = c("PI", "Comfort"))) %>%
  mutate(BodySegment = factor(BodySegment, levels = c("All", "LFoot", "RFoot", "LLowLeg", "RLowLeg", 
                                                      "LThigh", "RThigh", "Pelvis", "Head", "LHand",
                                                      "RHand", "LForearm", "RForearm", "LUpperArm", "RUpperArm",
                                                      "Chest", "Back"))) %>%
  mutate(Metric = factor(Metric, levels = c("T", "P")))

#head(data_all)
```

```{r}
ambient_upper1 <- read_csv("20211125_iButton1_temp.csv")
ambient_upper2 <- read_csv("20211125_iButton1_temp2.csv")
ambient_lower1 <- read_csv("20211125_iButton2_temp.csv")
ambient_lower2 <- read_csv("20211125_iButton2_temp2.csv")
ambient_upper3 <- read_csv("20211126_iButton1_temp.csv")
ambient_lower3 <- read_csv("20211126_iButton2_temp.csv")
ambient_upper4 <- read_csv("20211127_iButton1_temp.csv")
ambient_lower4 <- read_csv("20211127_iButton2_temp.csv")

ambient_upper <- ambient_upper1 %>%
  full_join(ambient_upper2) %>%
  full_join(ambient_upper3) %>%
  full_join(ambient_upper4) %>%
  select(-Unit) %>%
  rename(Temperature = Value) %>%
  mutate(Data = "iButton.Upper") %>%
  mutate(Time = mdy_hm(Time))

ambient_lower <- ambient_lower1 %>%
  full_join(ambient_lower2) %>%
  full_join(ambient_lower3) %>%
  full_join(ambient_lower4) %>%
  select(-Unit) %>%
  rename(Temperature = Value) %>%
  mutate(Data = "iButton.Lower") %>%
  mutate(Time = mdy_hm(Time))

ambient_all <- ambient_upper %>%
  full_join(ambient_lower)

```
```{r}
ggplot(ambient_all, aes(x = Time, y = Temperature)) + 
  geom_line(aes(colour = Data)) +
  theme_minimal()
```
```{r}
data_T_all <- data_all %>%
  filter(Metric == "T") %>%
  filter(BodySegment == "All")

plot_a <- ggplot(data_T_all, aes(x = factor(Chamber.SetPoint), y = value)) + 
  geom_hline(yintercept = 34, linetype = "dashed", colour = "#BBBBBB") +
  geom_boxplot(aes(fill = Setting, colour = Setting), outlier.shape = NA, alpha = 0.5) +
  facet_wrap(~ BodySegment) +
  scale_y_continuous(limits = c(27, 35), breaks = seq(27, 35, by = 2)) +
  scale_fill_manual(values = c("#9970AB", "#5AAE61")) +
  scale_colour_manual(values = c("#9970AB", "#5AAE61")) +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = c(0.5, 0.95), legend.title = element_blank(), legend.direction = "horizontal") +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line.y = element_line(colour = "#000000")) +
  xlab("") +
  ylab("Ts (degC)")

```


```{r}
data_T_segment <- data_all %>%
  filter(Metric == "T") %>%
  filter(BodySegment != "All")

plot_b <- ggplot(data_T_segment, aes(x = factor(Chamber.SetPoint), y = value)) + 
  geom_hline(yintercept = 34, linetype = "dashed", colour = "#BBBBBB") +
  geom_boxplot(aes(fill = Setting, colour = Setting), outlier.shape = NA, alpha = 0.5) +
  facet_wrap(~ BodySegment) +
  scale_y_continuous(limits = c(27, 35), breaks = seq(27, 35, by = 2)) +
  scale_fill_manual(values = c("#9970AB", "#5AAE61")) +
  scale_colour_manual(values = c("#9970AB", "#5AAE61")) +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line.y = element_line(colour = "#000000")) +
  xlab("") +
  ylab("")
```

```{r}
data_P_all <- data_all %>%
  filter(Metric == "P") %>%
  filter(BodySegment == "All")

plot_c <- ggplot(data_P_all, aes(x = factor(Chamber.SetPoint), y = value)) + 
  geom_boxplot(aes(fill = Setting, colour = Setting), outlier.shape = NA, alpha = 0.5) +
  #facet_wrap(~ BodySegment) +
  scale_fill_manual(values = c("#9970AB", "#5AAE61")) +
  scale_colour_manual(values = c("#9970AB", "#5AAE61")) +
  scale_y_continuous(limits = c(0,200), breaks = seq(0,200, by = 50)) +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none", legend.title = element_blank(), legend.direction = "horizontal") +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000")) +
  xlab("") +
  ylab("Power (W/m2)")

```


```{r}
data_P_segment <- data_all %>%
  filter(Metric == "P") %>%
  filter(BodySegment != "All")

plot_d <- ggplot(data_P_segment, aes(x = factor(Chamber.SetPoint), y = value)) + 
  geom_boxplot(aes(fill = Setting, colour = Setting), outlier.shape = NA, alpha = 0.5) +
  facet_wrap(~ BodySegment) +
  scale_fill_manual(values = c("#9970AB", "#5AAE61")) +
  scale_colour_manual(values = c("#9970AB", "#5AAE61")) +
  scale_y_continuous(limits = c(0,200), breaks = seq(0,200, by = 50)) +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "none") +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000")) +
  xlab("") +
  ylab("")
```

```{r}
ggarrange(plot_a+rremove("x.text"), plot_b+rremove("x.text"), plot_c, plot_d, ncol = 2, nrow = 2)
ggsave("ManikinControl.pdf", width = 8.5, height = 6.5, units = "in")
```

```{r}
data_start_all <- data_all %>%
  group_by(Chamber.SetPoint, Setting, BodySegment) %>%
  summarize(Start = min(Runtime.Min)) %>%
  ungroup()

data_T_norm_all <- data_T_all %>%
  left_join(data_start_all) %>%
  mutate(Runtime.norm = Runtime.Min - Start)

plot_e <- ggplot(data_T_norm_all, aes(x = Runtime.norm, y = value)) +
  geom_line(aes(colour = factor(Chamber.SetPoint), linetype = Setting)) +
  scale_colour_manual(values = c("#66CCEE", "#228833", "#CCBB44", "#EE6677")) +
  scale_x_continuous(limits = c(0,60)) +
  ylab("Ts (degC)") +
  xlab("") +
  facet_wrap(~ BodySegment) +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000"))


```

```{r}
data_T_norm_segment <- data_T_segment %>%
  left_join(data_start_all) %>%
  mutate(Runtime.norm = Runtime.Min - Start)

plot_f <- ggplot(data_T_norm_segment, aes(x = Runtime.norm, y = value)) +
  geom_line(aes(colour = BodySegment, linetype = Setting)) +
  facet_wrap(~ factor(Chamber.SetPoint)) +
  scale_x_continuous(limits = c(0,60)) +
  ylab("Ts (degC)") +
  xlab("") +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000"))

```
```{r}
data_P_norm_all <- data_P_all %>%
  left_join(data_start_all) %>%
  mutate(Runtime.norm = Runtime.Min - Start)

plot_g <- ggplot(data_P_norm_all, aes(x = Runtime.norm, y = value)) +
  geom_line(aes(colour = factor(Chamber.SetPoint), linetype = Setting)) +
  scale_x_continuous(limits = c(0,60)) +
  scale_colour_manual(values = c("#66CCEE", "#228833", "#CCBB44", "#EE6677")) +
  ylab("Power (W/m2)") +
  xlab("Runtime after steady state (min)") +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000"))
```

```{r}
data_P_norm_segment <- data_P_segment %>%
  left_join(data_start_all) %>%
  mutate(Runtime.norm = Runtime.Min - Start)

plot_h <- ggplot(data_P_norm_segment, aes(x = Runtime.norm, y = value)) +
  geom_line(aes(colour = BodySegment, linetype = Setting)) +
  facet_wrap(~ factor(Chamber.SetPoint)) +
  scale_x_continuous(limits = c(0,60)) +
  ylab("Power (W/m2)") +
  xlab("Runtime after steady state (min)") +
  theme_minimal() +
  theme(panel.grid = element_blank()) +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000"), axis.line = element_line(colour = "#000000"))
```

```{r}
left <- ggarrange(plot_e+rremove("x.text"), plot_g, common.legend = TRUE, ncol = 1, nrow = 2)
right <- ggarrange(plot_f+rremove("x.text"), plot_h, common.legend = TRUE, ncol = 1, nrow = 2)
full <- ggarrange(left, right)
ggsave("ManikinControl2.png", width = 8.5, height = 6.5, units = "in")
```

```{r}
data_thigh <- data32 %>%
  select(Time, Runtime, Runtime.Min, LThigh.T, LThigh.P, RThigh.T, RThigh.P) %>%
  pivot_longer(cols = ends_with(".T") | ends_with(".P"),
               names_to = c("BodySegment", "Metric"),
               names_sep = "[.]") %>%
  mutate(Metric = ifelse(Metric == "T", "Temperature", "Power")) %>%
  mutate(Metric = factor(Metric, levels = c("Temperature", "Power")))


ggplot(data_thigh, aes(x = Runtime.Min, y = value)) +
  annotate("rect", xmin = -Inf, xmax = 15, ymin = -Inf, ymax = Inf, fill = "#BBBBBB", alpha = 0.2) + 
  annotate("rect", xmin = 15, xmax = 115, ymin = -Inf, ymax = Inf, fill = "#CC79A7", alpha = 0.2) + 
  annotate("rect", xmin = 115, xmax = 130, ymin = -Inf, ymax = Inf, fill = "#BBBBBB", alpha = 0.2) +
  annotate("rect", xmin = 130, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "#009E73", alpha = 0.2) +
  annotate("text", x = 50, y = Inf, label = "PI") +
  annotate("text", x = 150, y = Inf, label = "Comfort") +
  geom_line(aes(colour = BodySegment)) +
  scale_colour_manual(values = c("#0072B2", "#D55E00")) +
  facet_grid(Metric~., scales = "free") +
  theme_minimal() +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000")) +
  ylab("") +
  xlab("Runtime (min)") +
  ggtitle("Ambient temperature = 32 deg C")

ggsave("thigh32.pdf", width = 6.5, height = 4, units = "in")
  
```

```{r}
data_thigh2 <- data28 %>%
  select(Time, Runtime, Runtime.Min, LThigh.T, LThigh.P, RThigh.T, RThigh.P) %>%
  pivot_longer(cols = ends_with(".T") | ends_with(".P"),
               names_to = c("BodySegment", "Metric"),
               names_sep = "[.]") %>%
  mutate(Metric = ifelse(Metric == "T", "Temperature", "Power")) %>%
  mutate(Metric = factor(Metric, levels = c("Temperature", "Power")))


ggplot(data_thigh2, aes(x = Runtime.Min, y = value)) +
  annotate("rect", xmin = -Inf, xmax = 30, ymin = -Inf, ymax = Inf, fill = "#BBBBBB", alpha = 0.2) + 
  annotate("rect", xmin = 30, xmax = 147, ymin = -Inf, ymax = Inf, fill = "#009E73", alpha = 0.2) + 
  annotate("rect", xmin = 147, xmax = 162, ymin = -Inf, ymax = Inf, fill = "#BBBBBB", alpha = 0.2) +
  annotate("rect", xmin = 162, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "#CC79A7", alpha = 0.2) +
  annotate("text", x = 100, y = Inf, label = "Comfort") +
  annotate("text", x = 180, y = Inf, label = "PI") +
  geom_line(aes(colour = BodySegment)) +
  scale_colour_manual(values = c("#0072B2", "#D55E00")) +
  facet_grid(Metric~., scales = "free") +
  theme_minimal() +
  theme(legend.position = "top", legend.title = element_blank()) +
  theme(panel.grid = element_blank()) +
  theme(text = element_text(size = 7, colour = "#000000")) +
  theme(axis.text = element_text(size = 7, colour = "#000000")) +
  ylab("") +
  xlab("Runtime (min)") +
  ggtitle("Ambient temperature = 28 deg C")
  
ggsave("thigh28.pdf", width = 6.5, height = 4, units = "in")
```

```{r}

data_start <- data_all %>%
  mutate(day = day(Time)) %>%
  group_by(day, Setting) %>%
  summarise(start = min(Runtime.Min))

reference <- read_csv("ReferenceSkin.csv")

data_subset <- data_all %>%
  filter(Chamber.SetPoint == 16 | Chamber.SetPoint == 28) %>%
  mutate(Metric = ifelse(Metric == "T", "Temperature", "Power")) %>%
  mutate(Metric = factor(Metric, levels = c("Temperature", "Power"))) %>%
  pivot_wider(names_from = Metric, values_from = value) %>%
  mutate(day = day(Time)) %>%
  left_join(data_start) %>%
  mutate(Runtime.norm = Runtime.Min - start) %>%
  left_join(reference) %>%
  mutate(day = ifelse(Setting == "Comfort", ifelse(day == 27 | day == 25, 34, 36.4), NA)) %>%
  rename(Tbody = day) %>%
  filter(Runtime.norm < 60) %>%
  filter(Setting != "PI")
```

```{r}
ggplot(data_subset, aes(x = Runtime.norm)) +
  geom_line(aes(y = Temperature,  colour = factor(Chamber.SetPoint))) +
  geom_line(aes(y = Zhang), linetype = "dashed") +
  geom_line(aes(y = OlesonFanger), linetype = "dotted") +
  facet_wrap(~BodySegment) + 
  theme_minimal() +
  theme(legend.position = "top", legend.title = element_blank()) +
  xlab("Runtime (min)")
```
```{r}
data_comfort <- data_subset %>%
  filter(Tbody == 36.4) %>%
  group_by(Chamber.SetPoint, BodySegment) %>%
  summarise(Ts = mean(Temperature)) %>%
  mutate(Ts = round(Ts, 1)) %>%
  left_join(reference) %>%
  pivot_wider(names_from = Chamber.SetPoint, names_prefix = "Chamber.SetPoint.", values_from = Ts)
```


