---
title: "Appendix: Power"
author: "Arfa Aijazi"
date: "3/2/2022"
output: github_document
---
Load libraries\
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(forecast)
library(zoo)
```

Load power data for all PCS\
```{r echo=TRUE, message=FALSE, warning=FALSE}
data_dir <- "data/Power"

colNames_hobo <- c("Chamber.SetPoint", "PCS", "Baseline", "Time", "Power", "Cycle")
data_files <- list.files(path = data_dir, pattern = "*.csv", full.names = TRUE)

data_all <- lapply(data_files, read_csv, col_types = cols())

PCS_data <- data_all %>%
  reduce(full_join) %>%
  mutate(Time = mdy_hms(Time)) %>%
  drop_na(Power) %>%
  mutate(Baseline = case_when(Baseline == TRUE ~ "Baseline",
                              Baseline == FALSE ~ "All Passive")) %>%
  mutate(Baseline = factor(Baseline, levels = c("Baseline", "All Passive")))
```
```{r include=FALSE}
theme_custom = function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(panel.background = element_rect(colour = "#BBBBBB")) +
    theme(plot.title = element_blank())
}
plot_colors <- c("#4477AA", "#CCBB44", "#228833", "#EE6677", "#AA3377", "#66CCEE")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(PCS_data, aes(x = Time, y = Power)) +
  geom_line(aes(colour = PCS, linetype = Baseline)) +
  scale_x_datetime(limits = c(mdy_hms("1/1/2000 0:00:00"), mdy_hms("1/1/2000 0:10:00"))) +
  facet_grid(Chamber.SetPoint~., scales = "free") +
  theme_custom() +
  guides(colour = guide_legend(nrow=2, byrow=TRUE)) +
  scale_colour_manual(values = plot_colors)
```
\
Heated blanket power is not periodic. Check rolling mean at different intervals (k = 1, 2, 5, 10, 20, 40, 60 minutes).\
```{r message=FALSE, warning=FALSE}

HeatedBlanket_data <- PCS_data %>%
  filter(PCS == "HeatedBlanket")

HeatedBlanket_rollmean <- HeatedBlanket_data %>%
  group_by(Baseline) %>%
  mutate(mean = mean(Power)) %>%
  mutate(rm.1 = rollmean(Power, k = 12, na.pad = TRUE, align = "right")) %>%
  mutate(rm.2 = rollmean(Power, k = 24, na.pad = TRUE, align = "right")) %>%
  mutate(rm.5 = rollmean(Power, k = 60, na.pad = TRUE, align = "right")) %>%
  mutate(rm.10 = rollmean(Power, k = 120, na.pad = TRUE, align = "right")) %>%
  mutate(rm.20 = rollmean(Power, k = 240, na.pad = TRUE, align = "right")) %>%
  mutate(rm.40 = rollmean(Power, k = 480, na.pad = TRUE, align = "right")) %>%
  mutate(rm.60 = rollmean(Power, k = 720, na.pad = TRUE, align = "right")) %>%
  pivot_longer(cols = starts_with("rm."), names_to = "k", names_prefix = "rm.", values_to = "rm") %>%
  mutate(k = as.numeric(k)) %>%
  mutate(k = factor(k))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(HeatedBlanket_rollmean, aes(x = Time, y = rm)) +
  geom_line(aes(colour = k)) +
  scale_colour_manual(values = c("#BBBBBB", "#B1A3B2", "#A68ca9", "#9b749f", "#8F5C96", "#83448D", "#762a83")) +
  facet_grid(.~Baseline, scales = "free") +
  xlab("") +
  ylab("Rolling mean of power (W)") +
  theme_custom()
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(HeatedBlanket_rollmean, aes(x = k, y = rm)) +
  geom_boxplot(aes(fill = k)) +
  scale_fill_manual(values = c("#BBBBBB", "#B1A3B2", "#A68ca9", "#9b749f", "#8F5C96", "#83448D", "#762a83")) +
  facet_grid(.~Baseline, scales = "free") +
  xlab("k (minutes)") +
  ylab("Rolling mean of power (W)") +
  theme_custom()
```

```{r message=FALSE, warning=FALSE}
PCS_avg <- PCS_data %>%
  group_by(Chamber.SetPoint, PCS, Baseline) %>%
  summarise(Mean.Power = mean(Power)) %>%
  mutate(Baseline = factor(Baseline, levels = c("All Passive", "Baseline"))) %>%
  mutate(Mean.Power = round(Mean.Power))
PCS_avg
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(PCS_avg, aes(x = reorder(PCS, Mean.Power), y = Mean.Power, group = Baseline)) +
  geom_col(aes(fill = PCS, alpha = Baseline), position = "dodge") +
  geom_text(aes(label = Mean.Power, group = Baseline), position = position_dodge(0.9), hjust = -0.25) +
  theme_custom() +
  guides(fill = guide_legend(nrow=2, byrow=TRUE)) +
  scale_y_continuous(limits = c(0, 150)) +
  scale_fill_manual(values = plot_colors) +
  ylab("Mean Power (W)") +
  xlab("") +
  coord_flip() +
  facet_grid(.~Chamber.SetPoint)
```

