---
title: "CaseStudy_Energy_Analysis"
output: github_notebook
date: "2022-12-18"
---


```{r message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(tidyverse)
library(lubridate)
library(knitr)
library(zoo)
library(forcats)
library(gridExtra)
library(Metrics)
library(comf)
library(ggpubr)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Set plot theme and colors
theme_custom = function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(strip.background = element_blank()) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(legend.title = element_blank()) +
    theme(text = element_text(size = 7, colour = "#000000")) +
    theme(plot.margin = margin(t = 0, r = 0.1, b = 0, l = 0.1))
}
```

```{r}
# Load energy model outputs
dalls_energy_file <- "./Dallas_EnergyModel/Dallas_Energy_Data.csv"
dallas_energy_epoutput <- read_csv(file = dalls_energy_file) 

dallas_energy <- dallas_energy_epoutput %>%
  mutate(Date = str_extract(Date.Time, "^[^\\s]+")) %>%
  mutate(Time = str_extract(Date.Time, "\\s.+")) %>%
  mutate(Date = paste0(Date,"/2021")) %>%
  mutate(Date.Time = paste(Date, Time, sep = " ")) %>%
  mutate(Date.Time = parse_date_time(Date.Time, "mdy_HMS")) %>%
  select(-Date, -Time) %>%
  filter(between(Date.Time, parse_date_time("2021-02-11", "ymd"), parse_date_time("2021-02-23", "ymd")))

analysisPeriod <- dallas_energy %>%
  filter(between(Date.Time, parse_date_time("2021-02-13 19:00:00", "ymd_HMS"), parse_date_time("2021-02-14 07:00:00", "ymd_HMS")))

dallas_energy <- analysisPeriod %>%
  mutate(T.skin_Baseline = 32.74228) %>%
  mutate(h.body_Baseline = 3.645669) %>%
  mutate(Q_Baseline_12.3 = h.body_Baseline*(T.skin_Baseline - T.Air_KDFW_Fixed_PassiveCombo_12.3)) %>%
  mutate(h.cal_Baseline = 7.976792) %>%
  mutate(T.eq_Baseline_12.3 = T.skin_Baseline - (Q_Baseline_12.3/h.cal_Baseline)) %>%
  mutate(T.skin_Passive = 34.60110) %>%
  mutate(h.body_Passive = 1.341360) %>%
  mutate(Q_Passive_12.3 = h.body_Passive*(T.skin_Passive - T.Air_KDFW_Fixed_PassiveCombo_12.3)) %>%
  mutate(h.cal_Passive = 7.621755) %>%
  mutate(T.eq_Passive_12.3 = T.skin_Passive - (Q_Passive_12.3/h.cal_Passive)) %>%
  mutate(thermal.effect_Passive_12.3 = T.eq_Passive_12.3 - T.eq_Baseline_12.3) %>%
  mutate(thermal.effect_Passive_12.3 = ifelse(hour(Date.Time) >= 22 | hour(Date.Time) <= 7, thermal.effect_Passive_12.3, 0)) %>%
  mutate(adj_T.Air_Passive_12.3 = T.Air_KDFW_Fixed_PassiveCombo_12.3 + thermal.effect_Passive_12.3) %>%
  mutate(Q_Baseline_13.9 = h.body_Baseline*(T.skin_Baseline - T.Air_KDFW_Fixed_HeatedBlanket_13.9)) %>%
  mutate(T.eq_Baseline_13.9 = T.skin_Baseline - (Q_Baseline_13.9/h.cal_Baseline)) %>%
  mutate(T.skin_HeatedBlanket = 34.05160) %>%
  mutate(h.body_HeatedBlanket = 1.992226) %>%
  mutate(Q_HeatedBlanket_13.9 = h.body_HeatedBlanket*(T.skin_HeatedBlanket - T.Air_KDFW_Fixed_HeatedBlanket_13.9)) %>%
  mutate(h.cal_HeatedBlanket = 7.976792) %>%
  mutate(T.eq_HeatedBlanket_13.9 = T.skin_HeatedBlanket - (Q_HeatedBlanket_13.9/h.cal_HeatedBlanket)) %>%
  mutate(thermal.effect_HeatedBlanket_13.9 = T.eq_HeatedBlanket_13.9 - T.eq_Baseline_13.9) %>%
  mutate(thermal.effect_HeatedBlanket_13.9 = ifelse(hour(Date.Time) >= 22 | hour(Date.Time) <= 7, thermal.effect_HeatedBlanket_13.9, 0)) %>%
  mutate(adj_T.Air_HeatedBlanket_13.9 = T.Air_KDFW_Fixed_HeatedBlanket_13.9 + thermal.effect_HeatedBlanket_13.9) %>%
  mutate(Q_Baseline_11.6 = h.body_Baseline*(T.skin_Baseline - T.Air_KDFW_Fixed_HeatedBlanketPassiveCombo_11.6)) %>%
  mutate(T.eq_Baseline_11.6 = T.skin_Baseline - (Q_Baseline_11.6/h.cal_Baseline)) %>%
  mutate(T.skin_HeatedBlanketPassive = 34.84524) %>%
  mutate(h.body_HeatedBlanketPassive = 1.120498) %>%
  mutate(Q_HeatedBlanketPassive_11.6 = h.body_HeatedBlanketPassive*(T.skin_HeatedBlanketPassive - T.Air_KDFW_Fixed_HeatedBlanketPassiveCombo_11.6)) %>%
  mutate(h.cal_HeatedBlanketPassive = 7.621755) %>%
  mutate(T.eq_HeatedBlanketPassive_11.6 = T.skin_HeatedBlanketPassive - (Q_HeatedBlanketPassive_11.6/h.cal_HeatedBlanketPassive)) %>%
  mutate(thermal.effect_HeatedBlanketPassive_11.6 = T.eq_HeatedBlanketPassive_11.6 - T.eq_Baseline_11.6) %>%
  mutate(thermal.effect_HeatedBlanketPassive_11.6 = ifelse(hour(Date.Time) >= 22 | hour(Date.Time) <= 7, thermal.effect_HeatedBlanketPassive_11.6, 0)) %>%
  mutate(adj_T.Air_HeatedBlanketPassive_11.6 = T.Air_KDFW_Fixed_HeatedBlanketPassiveCombo_11.6 + thermal.effect_HeatedBlanketPassive_11.6)

```

```{r}
# Check HVAC sizing approach
dallas_sizing <- dallas_energy %>%
  select(Date.Time, starts_with("T.Air_TMY3_"), starts_with("Electricity_TMY3")) %>%
  pivot_longer(cols = !Date.Time,
               names_to = c("Metric", "Weather", "Sizing", "Intervention" , "HeatingSetPoint"),
               names_sep = "_",
               values_to = "Value") %>%
  select(-Weather, -Intervention, -HeatingSetPoint) %>%
  mutate(Metric = factor(Metric, levels = c("T.Air", "Electricity")))

ggplot(dallas_sizing, aes(x = Date.Time, y = Value)) +
  geom_line(aes(colour = Sizing, linetype = Sizing)) +
  facet_grid(Metric~., scales = "free_y") +
  xlab("") +
  ylab("") +
  theme_custom()
  
```
```{r}
# Compare historical to actual weather
dallas_weather <- dallas_energy %>%
  select(Date.Time, starts_with("T.Outdoor"), ends_with("Fixed_None_22")) %>%
  rename(T_Indoor_TMY3 = T.Air_TMY3_Fixed_None_22,
         Electricity_Indoor_TMY3 = Electricity_TMY3_Fixed_None_22,
         T_Indoor_KDFW = T.Air_KDFW_Fixed_None_22,
         Electricity_Indoor_KDFW = Electricity_KDFW_Fixed_None_22,
         T_Outdoor_TMY3 = T.Outdoor_TMY3,
         T_Outdoor_KDFW = T.Outdoor_KDFW) %>%
  pivot_longer(cols = !Date.Time,
               names_to = c("Metric", "Location", "Weather"),
               names_sep = "_",
               values_to = "Value") %>%
  mutate(Metric = factor(Metric, levels = c("T", "Electricity"))) %>%
  mutate(Weather = factor(Weather, levels = c("TMY3", "KDFW")))

ggplot(dallas_weather, aes(x = Date.Time, y = Value)) +
  geom_line(aes(colour = Weather, linetype = Location)) + 
  facet_grid(Metric~., scales = "free_y") +
  xlab("") +
  ylab("") +
  theme_custom()
```
```{r}
# Compare interventions
dallas_interventions <- dallas_energy %>%
  select(Date.Time, T.Outdoor_KDFW, starts_with("T.Air_KDFW_Fixed"), starts_with("Electricity_KDFW_Fixed"), starts_with("adj")) %>%
  rename(T.Air_sim_None_22 = T.Air_KDFW_Fixed_None_22,
         T.Air_sim_None_18 = T.Air_KDFW_Fixed_None_18,
         T.Air_sim_PassiveCombo_12.3 = T.Air_KDFW_Fixed_PassiveCombo_12.3,
         T.Air_sim_HeatedBlanket_13.9 = T.Air_KDFW_Fixed_HeatedBlanket_13.9,
         T.Air_sim_HeatedBlanketPassiveCombo_11.6 = T.Air_KDFW_Fixed_HeatedBlanketPassiveCombo_11.6,
         T.Air_adj_PassiveCombo_12.3 = adj_T.Air_Passive_12.3,
         T.Air_adj_HeatedBlanket_13.9 = adj_T.Air_HeatedBlanket_13.9,
         T.Air_adj_HeatedBlanketPassiveCombo_11.6 = adj_T.Air_HeatedBlanketPassive_11.6,
         Electricity_sim_None_22 = Electricity_KDFW_Fixed_None_22,
         Electricity_sim_None_18 = Electricity_KDFW_Fixed_None_18,
         Electricity_sim_PassiveCombo_12.3 = Electricity_KDFW_Fixed_PassiveCombo_12.3,
         Electricity_sim_HeatedBlanket_13.9 = Electricity_KDFW_Fixed_HeatedBlanket_13.9,
         Electricity_sim_HeatedBlanketPassive_11.6 = Electricity_KDFW_Fixed_HeatedBlanketPassive_11.6,
         T.Air_KDFW_None_0 = T.Outdoor_KDFW) %>%
  select(-T.Air_sim_PassiveCombo_12.3, -T.Air_sim_HeatedBlanket_13.9, -T.Air_sim_HeatedBlanketPassiveCombo_11.6) %>%
  pivot_longer(cols = !Date.Time,
               names_to = c("Metric", "Source", "Intervention", "HeatingSetPoint"),
               names_sep = "_",
               values_to = "Value")

ggplot(dallas_interventions, aes(x = Date.Time, y = Value)) +
  geom_line(aes(colour = Intervention, linetype = HeatingSetPoint)) +
  facet_grid(Metric~., scales = "free_y") +
  xlab("") +
  ylab("") +
  theme_custom()
```


```{r}
dallas_energy_tab <- dallas_energy %>%
  select(Date.Time, starts_with("sim_")) %>%
  pivot_longer(cols = !Date.Time,
               names_to = c("Type", "Metric", "Intervention", "HeatingSetPoint"),
               names_sep = "_",
               values_to = "Value") %>%
  filter(Metric == "Electricity") %>%
  filter(between(Date.Time, parse_date_time("2021-02-14", "ymd"), parse_date_time("2021-02-20", "ymd"))) %>%
  select(Date.Time, HeatingSetPoint, Value) %>% 
  group_by(HeatingSetPoint) %>%
  summarise(TotalEnergy = sum(Value), PeakEnergy = max(Value)) %>%
  mutate(TotalEnergy = TotalEnergy*9e-7) %>%
  mutate(PeakEnergy = PeakEnergy*9e-7) %>%
  # mutate(Label = case_when(HeatingSetPoint == 22 ~ "None - 22C",
  #                          HeatingSetPoint == 18 ~ "None - 18C",
  #                          HeatingSetPoint == 13.9 ~ "Heated Blanket",
  #                          HeatingSetPoint == 12.3 ~ "Passive combination",
  #                          HeatingSetPoint == 11.6 ~ "Passive combination + Heated blanket")) %>%
  mutate(percChange_TotalEnergy = round(100*(TotalEnergy-3421.812)/3421.812)) %>%
  mutate(percChange_PeakEnergy = round(100*(PeakEnergy-28.77739)/28.77739))

dallas_energy_tab

```

