---
title: "Karachi"
author: "Arfa Aijazi"
date: '2022-11-01'
output: github_notebook
---

```{r message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
library(tidyverse)
library(lubridate)
library(knitr)
library(ggpubr)
library(zoo)
library(broom)
library(scales)
library(Metrics)
library(comf)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Set plot theme and colors
theme_custom = function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(strip.background = element_blank()) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(legend.title = element_blank()) +
    theme(axis.title = element_blank()) +
    theme(text = element_text(size = 7, colour = "#000000"))
}
```

```{r}
# Read in metadata from Github as data table
df_meta <- read_csv("https://github.com/CenterForTheBuiltEnvironment/ashrae-db-II/raw/master/v2.1.0/db_metadata.csv")

# Read in database from Github as data table
df_measurements <- read_csv("https://github.com/CenterForTheBuiltEnvironment/ashrae-db-II/raw/master/v2.1.0/db_measurements_v2.1.0.csv.gz")
```
```{r}
# Subset records with indoor air temperature and meteorological data
df_acm2 <- df_measurements %>%
  filter(!is.na(ta) & 
           (!is.na(t_out_isd)|!is.na(t_out)))

# Collapse outdoor met data
df_acm2 <- df_acm2 %>%
  mutate(t_out_combined = case_when(!is.na(t_out_isd) ~ t_out_isd,
                                    is.na(t_out_isd) & !is.na(t_out) ~ t_out,
                                    TRUE ~ NA_real_)) %>%
  select(-c(t_out_isd, t_out))

# Add relevant parameters from metadata table
df_acm2 <- df_meta %>%
  select(building_id, region, country, city, building_type, cooling_type, records, climate) %>%
  left_join(df_acm2, ., by = "building_id")

# Subset records from multifamily buildings in hot arid or semi-arid climate
df_karachi <- df_acm2 %>%
  filter(building_type == "multifamily housing") %>%
  filter(climate == "hot semi-arid" | climate == "desert (hot arid)") %>%
  filter(cooling_type == "naturally ventilated") %>%
  select(building_id, building_type, cooling_type, region, country, city, climate, timestamp, season, ta, top, rh, t_out_combined)
```

```{r}
lm_karachi <- lm(ta ~ t_out_combined, data = df_karachi)
summary(lm_karachi)

a <- lm_karachi$coefficients[2]
b <- lm_karachi$coefficients[1]
r2 <- summary(lm_karachi)$r.squared
MAE <- mae(df_karachi$ta, predict(lm_karachi))
```


```{r}
ggplot(df_karachi, aes(x = t_out_combined, y = ta)) + 
  xlim(9, 40) +
  ylim(9, 40) +
  xlab("Outdoor air temperature, To (C)") +
  ylab("Indoor air temperature, Ta (C)") +
  geom_point(colour = "#bbbbbb") +
  geom_smooth(method = "lm", se = FALSE, colour = "#DDAA33") +
  annotate("text", x = 10, y = 40, label = paste0("Ta = ", round(a, 1)," x To + ", round(b, 1)), colour = "#4d4d4d") +
  annotate("text", x = 10, y = 38, label = paste0("MAE = ", round(MAE, 1), "C"), colour = "#4d4d4d") +
  annotate("text", x = 10, y = 36, label = paste0("R2 = ", round(r2, 2)), colour = "#4d4d4d") +
  annotate("text", x = 30, y = 10, label = paste0("Based on ", nrow(df_karachi), " observations of naturally ventilated multifamily housing in hot semi-arid climate"), colour = "#4d4d4d") +
  theme_custom()

ggsave("lm_Karachi.pdf", width = 4, height = 4, units = "in")
```

```{r}
historical_file <- "Karachi_June2015_NASA.csv"
karachi_June2015 <- read.csv(file = historical_file, header = TRUE, skip = 14) %>%
  unite("Date", 1:2, sep = " ") %>%
  rename(DBT = Dry.Bulb.Temperature..C.) %>%
  rename(RH_DBT = Relative.Humidity....) %>%
  select(Date, DBT, RH_DBT) %>%
  mutate(Date = parse_date_time(Date, "ymd_HM")) %>%
  mutate(T.Air = (DBT * a) + b) %>%
  mutate(ps_DBT = 610.78*exp(DBT/(DBT + 238.3) * 17.2694)) %>%
  mutate(p = (RH_DBT/100) * ps_DBT) %>%
  mutate(ps_T.Air = 610.78*exp(T.Air/(T.Air + 238.3) * 17.2694)) %>%
  mutate(RH_T.Air = (p/ps_T.Air)*100) 

```
```{r}
baselineCond <- createCond()
baselineCond$ta <- karachi_June2015$T.Air
baselineCond$tr <- karachi_June2015$T.Air
baselineCond$vel <- 0.1
baselineCond$rh <- karachi_June2015$RH_T.Air
baselineCond$met <- 0.7
baselineCond$clo <- 1.2

baselineSET <- calcComfInd(baselineCond, request = "set") 
karachi_June2015$baseline <- baselineSET$set
```

```{r}
passiveCond <- createCond()
passiveCond$ta <- karachi_June2015$T.Air
passiveCond$tr <- karachi_June2015$T.Air
passiveCond$vel <- 0.1
passiveCond$rh <- karachi_June2015$RH_T.Air
passiveCond$met <- 0.7
passiveCond$clo <- 0.34

passiveSET <- calcComfInd(passiveCond, request = "set") 
karachi_June2015$passiveSET <- passiveSET$set
```

```{r}
ceilingFanCond <- createCond()
ceilingFanCond$ta <- karachi_June2015$T.Air
ceilingFanCond$tr <- karachi_June2015$T.Air
ceilingFanCond$vel <- 0.4
ceilingFanCond$rh <- karachi_June2015$RH_T.Air
ceilingFanCond$met <- 0.7
ceilingFanCond$clo <- 1.2

ceilingFanSET <- calcComfInd(ceilingFanCond, request = "set") 
karachi_June2015$ceilingFanSET <- ceilingFanSET$set
```

```{r}
ceilingFanPassiveCond <- createCond()
ceilingFanPassiveCond$ta <- karachi_June2015$T.Air
ceilingFanPassiveCond$tr <- karachi_June2015$T.Air
ceilingFanPassiveCond$vel <- 0.4
ceilingFanPassiveCond$rh <- karachi_June2015$RH_T.Air
ceilingFanPassiveCond$met <- 0.7
ceilingFanPassiveCond$clo <- 0.34

ceilingFanPassiveSET <- calcComfInd(ceilingFanPassiveCond, request = "set") 
karachi_June2015$ceilingFanPassiveSET <- ceilingFanPassiveSET$set
```

```{r}
karachi_June2015 <- karachi_June2015 %>%
  filter(between(Date, parse_date_time("2015-06-14", "ymd"), parse_date_time("2015-06-27", "ymd"))) %>%
  pivot_longer(ends_with("SET"), names_to = "Type", values_to = "SET") %>%
  mutate(CoolingEffect = baseline - SET) %>%
  mutate(CoolingEffect = ifelse(between(Date, parse_date_time("2015-06-17", "ymd"), parse_date_time("2015-06-24", "ymd")), CoolingEffect, 0)) %>%
mutate(CoolingEffect = ifelse(hour(Date) >= 22 | hour(Date) < 7, CoolingEffect, 0))%>%
  mutate(Type = substring(Type, 1, nchar(Type)-3)) %>%
  mutate(T.Air2 = T.Air - CoolingEffect) %>%
  select(Date, DBT, T.Air, Type, T.Air2) %>%
  pivot_wider(names_from = Type, values_from = T.Air2) %>%
  rename(T.Air_None = T.Air, T.Air_Passive = passive, T.Air_ceilingFan = ceilingFan, T.Air_ceilingFanPassive = ceilingFanPassive)
  
```

```{r}
karachi_exposure <- karachi_June2015 %>%
  filter(between(Date, parse_date_time("2015-06-17", "ymd"), parse_date_time("2015-06-24", "ymd"))) %>%
  select(Date, starts_with("T.Air")) %>%
  pivot_longer(!Date, names_to = "Type", values_to = "Temperature") %>%
  mutate(exposure = Temperature - 28) %>%
  mutate(exposure = ifelse(exposure > 0, exposure, 0)) %>%
  group_by(Type) %>%
  mutate(Type = factor(Type, levels = c("T.Air_None", "T.Air_Passive", "T.Air_ceilingFan", "T.Air_ceilingFanPassive"))) %>%
  summarise(exposure = sum(exposure)) %>%
  mutate(exposure = round(exposure, 0)) %>%
  mutate(percent.reduction = (exposure - karachi_exposure$exposure[1])/karachi_exposure$exposure[1]*100) 
```



```{r}
karachi_June2015_plot <- karachi_June2015 %>% 
  select(Date, DBT, T.Air_None, T.Air_ceilingFanPassive) %>%
  pivot_longer(!Date, names_to = "Type", values_to = "Temperature") %>%
  mutate(Type = factor(Type, levels = c("DBT", "T.Air_None", "T.Air_ceilingFanPassive")))

ggplot(karachi_June2015_plot, aes(x = Date, y = Temperature)) + 
  annotate("rect", xmin = parse_date_time("2015-06-17 0:00", "ymd_HM"), xmax = parse_date_time("2015-06-24 0:00", "ymd_HM"), ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "#bbbbbb") +
  annotate("text", x = parse_date_time("2015-06-17 12:00", "ymd_HM"), y = Inf, label = "Heat Wave") +
  geom_line(aes(linetype = Type, colour = Type)) +
  scale_colour_manual(values = c("#FDDBC7", "#000000", "#495893")) +
  geom_hline(yintercept = 30, linewidth = 0.25, colour = "#e7d4e8") +
  scale_x_datetime(date_breaks = "1 day", date_labels = "%b %d", limits = c(parse_date_time("2015-06-14", "ymd"), parse_date_time("2015-06-27", "ymd"))) +
  theme_custom()

ggsave("Karachi_plot.pdf", width = 6.5, height = 4, units = "in")
```